const materials = [
  "Aluminum",
  "Brass",
  "Stainless Steel",
  "Plastic",
  "Bakelite",
  "Copper",
  "Rubber",
  "Silicone",
  "Fiber",
  "Glass",
  "Ceramic",
  "Wood",
  "Composite",
  "Steel",
  "Acrylic Paint",
  "Oil-based Paint",
  "Water-based Paint",
  "Spray Paint",
  "Concrete",
  "Mortar",
  "Grout",
  "Cement",
  "Plaster",
  "Stucco",
  "Adhesive",
  "Epoxy Resin",
  "Joint Compound",
  "Render",
  "Sealant",
  "Waterproofing Membrane",
];
export default materials;
